/* Generated by Yosys 0.19+36 (git sha1 6f792e2223c, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module iiitb_tlc(light_highway, light_farm, C, clk, rst_n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input C;
  wire C;
  input clk;
  wire clk;
  output [2:0] light_farm;
  wire [2:0] light_farm;
  output [2:0] light_highway;
  wire [2:0] light_highway;
  wire [1:0] next_state;
  input rst_n;
  wire rst_n;
  wire [1:0] state;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(state[1]),
    .Y(light_farm[2])
  );
  sky130_fd_sc_hd__nor2_1 _05_ (
    .A(state[0]),
    .B(light_farm[2]),
    .Y(light_farm[0])
  );
  sky130_fd_sc_hd__nor2_1 _06_ (
    .A(state[1]),
    .B(state[0]),
    .Y(light_highway[0])
  );
  sky130_fd_sc_hd__nor2_1 _07_ (
    .A(state[1]),
    .B(C),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(state[0]),
    .B(_00_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(state[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _10_ (
    .A(_01_),
    .B(state[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__or2b_2 _11_ (
    .A(state[1]),
    .B_N(state[0]),
    .X(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _12_ (
    .A(_02_),
    .B(_03_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(light_farm[2]),
    .B(_01_),
    .Y(light_farm[1])
  );
  sky130_fd_sc_hd__clkinv_1 _14_ (
    .A(_03_),
    .Y(light_highway[1])
  );
  sky130_fd_sc_hd__buf_1 _15_ (
    .A(state[1]),
    .X(light_highway[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
endmodule
