/* Generated by Yosys 0.19+36 (git sha1 6f792e2223c, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module iiitb_tlc(light_highway, light_farm, C, clk, rst_n);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  input C;
  wire C;
  input clk;
  wire clk;
  wire [27:0] count;
  wire [27:0] count_delay;
  wire delay10s;
  wire delay3s1;
  wire delay3s2;
  output [2:0] light_farm;
  wire [2:0] light_farm;
  output [2:0] light_highway;
  wire [2:0] light_highway;
  wire [1:0] next_state;
  input rst_n;
  wire rst_n;
  wire [1:0] state;
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(state[0]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(state[1]),
    .Y(light_farm[2])
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(_059_),
    .B(light_farm[2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(_060_),
    .Y(light_highway[0])
  );
  sky130_fd_sc_hd__nor3_1 _327_ (
    .A(delay3s2),
    .B(_059_),
    .C(light_farm[2]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(_059_),
    .B(state[1]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _329_ (
    .A(_062_),
    .Y(light_farm[0])
  );
  sky130_fd_sc_hd__a21oi_1 _330_ (
    .A1(light_farm[0]),
    .A2(delay10s),
    .B1(_061_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(light_highway[0]),
    .B(C),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o311ai_0 _332_ (
    .A1(_059_),
    .A2(state[1]),
    .A3(delay3s1),
    .B1(_064_),
    .C1(_063_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(state[1]),
    .B(_059_),
    .Y(light_highway[1])
  );
  sky130_fd_sc_hd__a21oi_1 _334_ (
    .A1(light_highway[1]),
    .A2(delay3s1),
    .B1(_061_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_065_),
    .B(_062_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_059_),
    .B(light_farm[2]),
    .Y(light_farm[1])
  );
  sky130_fd_sc_hd__clkinv_1 _337_ (
    .A(count[25]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(count[24]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(count[27]),
    .B(count[26]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand3_1 _340_ (
    .A(_068_),
    .B(_066_),
    .C(_067_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(count[21]),
    .B(count[20]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(count[23]),
    .B(count[22]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(count[17]),
    .B(count[16]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(count[19]),
    .B(count[18]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand4_1 _345_ (
    .A(_070_),
    .B(_071_),
    .C(_072_),
    .D(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _346_ (
    .A(_069_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(count[5]),
    .B(count[4]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _348_ (
    .A(count[7]),
    .B(count[6]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor3_1 _350_ (
    .A(count[3]),
    .B(count[2]),
    .C(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _351_ (
    .A(_079_),
    .B(_076_),
    .C(_077_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _352_ (
    .A(count[13]),
    .B(count[12]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(count[15]),
    .B(count[14]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(count[9]),
    .B(count[8]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(count[11]),
    .B(count[10]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4_1 _356_ (
    .A(_081_),
    .B(_082_),
    .C(_083_),
    .D(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(_085_),
    .B(_080_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand3_1 _358_ (
    .A(_086_),
    .B(_060_),
    .C(_075_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_087_),
    .B(count_delay[0]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(count_delay[0]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(count_delay[25]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(count_delay[24]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(count_delay[27]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _364_ (
    .A(count_delay[26]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand4_1 _365_ (
    .A(_090_),
    .B(_091_),
    .C(_092_),
    .D(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _366_ (
    .A(count_delay[21]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _367_ (
    .A(count_delay[22]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(count_delay[20]),
    .B(count_delay[23]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand3_1 _369_ (
    .A(_097_),
    .B(_095_),
    .C(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _370_ (
    .A(count_delay[17]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _371_ (
    .A(count_delay[16]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _372_ (
    .A(count_delay[19]),
    .B(count_delay[18]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand3_1 _373_ (
    .A(_101_),
    .B(_099_),
    .C(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor3_1 _374_ (
    .A(_098_),
    .B(_102_),
    .C(_094_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__clkinv_1 _375_ (
    .A(count_delay[13]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _376_ (
    .A(count_delay[12]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__clkinv_1 _377_ (
    .A(count_delay[15]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(count_delay[14]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4_1 _379_ (
    .A(_104_),
    .B(_105_),
    .C(_106_),
    .D(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__clkinv_1 _380_ (
    .A(count_delay[9]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(count_delay[8]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(count_delay[11]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(count_delay[10]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand4_1 _384_ (
    .A(_109_),
    .B(_110_),
    .C(_111_),
    .D(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(_108_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(count_delay[5]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(count_delay[4]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor2_1 _388_ (
    .A(count_delay[7]),
    .B(count_delay[6]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand3_1 _389_ (
    .A(_117_),
    .B(_115_),
    .C(_116_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__clkinv_1 _390_ (
    .A(count_delay[2]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(count_delay[3]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _392_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _393_ (
    .A(_089_),
    .B(count_delay[1]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor3_1 _394_ (
    .A(_122_),
    .B(_121_),
    .C(_118_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand4_1 _395_ (
    .A(_103_),
    .B(light_highway[1]),
    .C(_114_),
    .D(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _396_ (
    .A(count_delay[1]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand4_1 _397_ (
    .A(_125_),
    .B(_119_),
    .C(count_delay[0]),
    .D(count_delay[3]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(_118_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand4_1 _399_ (
    .A(_103_),
    .B(light_farm[0]),
    .C(_114_),
    .D(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand4_1 _400_ (
    .A(_103_),
    .B(light_farm[1]),
    .C(_114_),
    .D(_123_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand4_1 _401_ (
    .A(_124_),
    .B(_128_),
    .C(_129_),
    .D(_089_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _402_ (
    .A1(_087_),
    .A2(_130_),
    .B1(_088_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(_087_),
    .B(count_delay[1]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(_125_),
    .B(count_delay[0]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(_132_),
    .B(_122_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand4_1 _406_ (
    .A(_124_),
    .B(_128_),
    .C(_129_),
    .D(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(_087_),
    .A2(_134_),
    .B1(_131_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_087_),
    .B(count_delay[2]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(count_delay[0]),
    .B(count_delay[1]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xor2_1 _410_ (
    .A(count_delay[2]),
    .B(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__o21ai_0 _411_ (
    .A1(_087_),
    .A2(_137_),
    .B1(_135_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _412_ (
    .A(_087_),
    .B(count_delay[3]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(_119_),
    .B(_136_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_1 _414_ (
    .A(count_delay[3]),
    .B(_139_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nand4_1 _415_ (
    .A(_124_),
    .B(_128_),
    .C(_129_),
    .D(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _416_ (
    .A1(_087_),
    .A2(_141_),
    .B1(_138_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(_087_),
    .B(count_delay[4]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand4_1 _418_ (
    .A(count_delay[0]),
    .B(count_delay[1]),
    .C(count_delay[2]),
    .D(count_delay[3]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _419_ (
    .A(count_delay[4]),
    .B(_143_),
    .X(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _420_ (
    .A1(_087_),
    .A2(_144_),
    .B1(_142_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(_087_),
    .B(count_delay[5]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _422_ (
    .A(_116_),
    .B(_143_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xor2_1 _423_ (
    .A(_115_),
    .B(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__o21ai_0 _424_ (
    .A1(_087_),
    .A2(_147_),
    .B1(_145_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _425_ (
    .A(_087_),
    .B(count_delay[6]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor3_1 _426_ (
    .A(_115_),
    .B(_116_),
    .C(_143_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xnor2_1 _427_ (
    .A(count_delay[6]),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _428_ (
    .A1(_087_),
    .A2(_150_),
    .B1(_148_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(_087_),
    .B(count_delay[7]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(_149_),
    .B(count_delay[6]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xor2_1 _431_ (
    .A(count_delay[7]),
    .B(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _432_ (
    .A1(_087_),
    .A2(_153_),
    .B1(_151_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_087_),
    .B(count_delay[8]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand4_1 _434_ (
    .A(count_delay[5]),
    .B(count_delay[4]),
    .C(count_delay[7]),
    .D(count_delay[6]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _435_ (
    .A(_143_),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _436_ (
    .A(_110_),
    .B(_156_),
    .X(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _437_ (
    .A1(_087_),
    .A2(_157_),
    .B1(_154_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _438_ (
    .A(_087_),
    .B(count_delay[9]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_156_),
    .B(count_delay[8]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xor2_1 _440_ (
    .A(count_delay[9]),
    .B(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(_087_),
    .A2(_160_),
    .B1(_158_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(_087_),
    .B(count_delay[10]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(count_delay[9]),
    .B(count_delay[8]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__clkinv_1 _444_ (
    .A(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(_156_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__xor2_1 _446_ (
    .A(count_delay[10]),
    .B(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(_087_),
    .A2(_165_),
    .B1(_161_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(_087_),
    .B(count_delay[11]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand3_1 _449_ (
    .A(_156_),
    .B(count_delay[10]),
    .C(_163_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _450_ (
    .A(count_delay[11]),
    .B(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(_087_),
    .A2(_168_),
    .B1(_166_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(_087_),
    .B(count_delay[12]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand4_1 _453_ (
    .A(count_delay[9]),
    .B(count_delay[8]),
    .C(count_delay[11]),
    .D(count_delay[10]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor3_1 _454_ (
    .A(_143_),
    .B(_155_),
    .C(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xor2_1 _455_ (
    .A(_105_),
    .B(_171_),
    .X(_172_)
  );
  sky130_fd_sc_hd__o21ai_0 _456_ (
    .A1(_087_),
    .A2(_172_),
    .B1(_169_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(_087_),
    .B(count_delay[13]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(_171_),
    .B(count_delay[12]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _459_ (
    .A(count_delay[13]),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _460_ (
    .A1(_171_),
    .A2(count_delay[12]),
    .B1(_104_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(_176_),
    .B(_175_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__o21ai_0 _462_ (
    .A1(_087_),
    .A2(_177_),
    .B1(_173_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(_087_),
    .B(count_delay[14]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(_104_),
    .B(_105_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _465_ (
    .A1(_171_),
    .A2(_179_),
    .B1(_107_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(_171_),
    .B(_179_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(count_delay[14]),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(_180_),
    .B(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _469_ (
    .A1(_087_),
    .A2(_183_),
    .B1(_178_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(_087_),
    .B(count_delay[15]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__and3_2 _471_ (
    .A(_086_),
    .B(_060_),
    .C(_075_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor3_1 _472_ (
    .A(count_delay[15]),
    .B(_107_),
    .C(_181_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a31oi_1 _473_ (
    .A1(_171_),
    .A2(count_delay[14]),
    .A3(_179_),
    .B1(_106_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21ai_0 _474_ (
    .A1(_187_),
    .A2(_186_),
    .B1(_185_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _475_ (
    .A(_188_),
    .B(_184_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(_087_),
    .B(count_delay[16]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand4_1 _477_ (
    .A(count_delay[13]),
    .B(count_delay[12]),
    .C(count_delay[15]),
    .D(count_delay[14]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _478_ (
    .A(_170_),
    .B(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(_156_),
    .B(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__xor2_1 _480_ (
    .A(count_delay[16]),
    .B(_192_),
    .X(_193_)
  );
  sky130_fd_sc_hd__o21ai_0 _481_ (
    .A1(_087_),
    .A2(_193_),
    .B1(_189_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(_087_),
    .B(count_delay[17]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor3_1 _483_ (
    .A(count_delay[17]),
    .B(_100_),
    .C(_192_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor4_1 _484_ (
    .A(_143_),
    .B(_155_),
    .C(_170_),
    .D(_190_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a21oi_1 _485_ (
    .A1(_196_),
    .A2(count_delay[16]),
    .B1(_099_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _486_ (
    .A(_195_),
    .B(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__o21ai_0 _487_ (
    .A1(_087_),
    .A2(_198_),
    .B1(_194_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(_087_),
    .B(count_delay[18]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__clkinv_1 _489_ (
    .A(count_delay[18]),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(count_delay[17]),
    .B(count_delay[16]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__clkinv_1 _491_ (
    .A(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a21oi_1 _492_ (
    .A1(_196_),
    .A2(_202_),
    .B1(_200_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand3_1 _493_ (
    .A(_156_),
    .B(_191_),
    .C(_202_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _494_ (
    .A(count_delay[18]),
    .B(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _495_ (
    .A(_205_),
    .B(_203_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _496_ (
    .A1(_087_),
    .A2(_206_),
    .B1(_199_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_087_),
    .B(count_delay[19]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nor3_1 _498_ (
    .A(count_delay[19]),
    .B(_200_),
    .C(_204_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21a_1 _499_ (
    .A1(_200_),
    .A2(_204_),
    .B1(count_delay[19]),
    .X(_209_)
  );
  sky130_fd_sc_hd__o21ai_0 _500_ (
    .A1(_208_),
    .A2(_209_),
    .B1(_185_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _501_ (
    .A(_210_),
    .B(_207_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _502_ (
    .A(_087_),
    .B(count_delay[20]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand4_1 _503_ (
    .A(count_delay[17]),
    .B(count_delay[16]),
    .C(count_delay[19]),
    .D(count_delay[18]),
    .Y(_212_)
  );
  sky130_fd_sc_hd__clkinv_1 _504_ (
    .A(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand3_1 _505_ (
    .A(_156_),
    .B(_191_),
    .C(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__xor2_1 _506_ (
    .A(count_delay[20]),
    .B(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__o21ai_0 _507_ (
    .A1(_087_),
    .A2(_215_),
    .B1(_211_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _508_ (
    .A(_087_),
    .B(count_delay[21]),
    .Y(_216_)
  );
  sky130_fd_sc_hd__clkinv_1 _509_ (
    .A(count_delay[20]),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor3_1 _510_ (
    .A(count_delay[21]),
    .B(_217_),
    .C(_214_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a31oi_1 _511_ (
    .A1(_196_),
    .A2(count_delay[20]),
    .A3(_213_),
    .B1(_095_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21ai_0 _512_ (
    .A1(_218_),
    .A2(_219_),
    .B1(_185_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _513_ (
    .A(_220_),
    .B(_216_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(_087_),
    .B(count_delay[22]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _515_ (
    .A(_095_),
    .B(_217_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand4_1 _516_ (
    .A(_156_),
    .B(_191_),
    .C(_213_),
    .D(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__and2_2 _517_ (
    .A(_223_),
    .B(count_delay[22]),
    .X(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _518_ (
    .A(count_delay[22]),
    .B(_223_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o21ai_0 _519_ (
    .A1(_225_),
    .A2(_224_),
    .B1(_185_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2_1 _520_ (
    .A(_226_),
    .B(_221_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _521_ (
    .A(_087_),
    .B(count_delay[23]),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nor3_1 _522_ (
    .A(count_delay[23]),
    .B(_096_),
    .C(_223_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__o21a_1 _523_ (
    .A1(_096_),
    .A2(_223_),
    .B1(count_delay[23]),
    .X(_229_)
  );
  sky130_fd_sc_hd__o21ai_0 _524_ (
    .A1(_228_),
    .A2(_229_),
    .B1(_185_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nand2_1 _525_ (
    .A(_230_),
    .B(_227_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _526_ (
    .A(_087_),
    .B(count_delay[24]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand4_1 _527_ (
    .A(count_delay[21]),
    .B(count_delay[20]),
    .C(count_delay[23]),
    .D(count_delay[22]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nor2_1 _528_ (
    .A(_212_),
    .B(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21oi_1 _529_ (
    .A1(_196_),
    .A2(_233_),
    .B1(_091_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand3_1 _530_ (
    .A(_156_),
    .B(_191_),
    .C(_233_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor2_1 _531_ (
    .A(count_delay[24]),
    .B(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nor2_1 _532_ (
    .A(_236_),
    .B(_234_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__o21ai_0 _533_ (
    .A1(_087_),
    .A2(_237_),
    .B1(_231_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(_087_),
    .B(count_delay[25]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor3_1 _535_ (
    .A(count_delay[25]),
    .B(_091_),
    .C(_235_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__a31oi_1 _536_ (
    .A1(_196_),
    .A2(count_delay[24]),
    .A3(_233_),
    .B1(_090_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__o21ai_0 _537_ (
    .A1(_239_),
    .A2(_240_),
    .B1(_185_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(_241_),
    .B(_238_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _539_ (
    .A(_087_),
    .B(count_delay[26]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor2_1 _540_ (
    .A(_090_),
    .B(_091_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a41oi_1 _541_ (
    .A1(_156_),
    .A2(_191_),
    .A3(_233_),
    .A4(_243_),
    .B1(_093_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand4_1 _542_ (
    .A(_156_),
    .B(_191_),
    .C(_233_),
    .D(_243_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nor2_1 _543_ (
    .A(count_delay[26]),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor2_1 _544_ (
    .A(_244_),
    .B(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__o21ai_0 _545_ (
    .A1(_087_),
    .A2(_247_),
    .B1(_242_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _546_ (
    .A(_087_),
    .B(count_delay[27]),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor3_1 _547_ (
    .A(count_delay[27]),
    .B(_093_),
    .C(_245_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__a41oi_1 _548_ (
    .A1(_196_),
    .A2(count_delay[26]),
    .A3(_233_),
    .A4(_243_),
    .B1(_092_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__o21bai_1 _549_ (
    .A1(_249_),
    .A2(_250_),
    .B1_N(_087_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nand2_1 _550_ (
    .A(_251_),
    .B(_248_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _551_ (
    .A(_086_),
    .B(_075_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand2_1 _552_ (
    .A(_252_),
    .B(delay10s),
    .Y(_253_)
  );
  sky130_fd_sc_hd__o21ai_0 _553_ (
    .A1(_252_),
    .A2(_128_),
    .B1(_253_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _554_ (
    .A(_252_),
    .B(delay3s1),
    .Y(_254_)
  );
  sky130_fd_sc_hd__o21ai_0 _555_ (
    .A1(_252_),
    .A2(_124_),
    .B1(_254_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(_252_),
    .B(delay3s2),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o21ai_0 _557_ (
    .A1(_252_),
    .A2(_129_),
    .B1(_255_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _558_ (
    .A(count[0]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _559_ (
    .A(_078_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _560_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor2_1 _561_ (
    .A(_257_),
    .B(_256_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _562_ (
    .A(count[2]),
    .B(_256_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__clkinv_1 _563_ (
    .A(count[2]),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _564_ (
    .A(_259_),
    .B(_078_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a211oi_1 _565_ (
    .A1(_086_),
    .A2(_075_),
    .B1(_258_),
    .C1(_260_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xor2_1 _566_ (
    .A(count[3]),
    .B(_260_),
    .X(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _567_ (
    .A(count[4]),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nand2_1 _568_ (
    .A(_260_),
    .B(count[3]),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _569_ (
    .A(_261_),
    .B(_262_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__a21oi_1 _570_ (
    .A1(_260_),
    .A2(count[3]),
    .B1(count[4]),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor2_1 _571_ (
    .A(_264_),
    .B(_263_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _572_ (
    .A(count[5]),
    .B(_263_),
    .X(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _573_ (
    .A(count[6]),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nand2_1 _574_ (
    .A(_263_),
    .B(count[5]),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nor2_1 _575_ (
    .A(_265_),
    .B(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a21oi_1 _576_ (
    .A1(_263_),
    .A2(count[5]),
    .B1(count[6]),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _577_ (
    .A(_268_),
    .B(_267_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _578_ (
    .A(count[7]),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _579_ (
    .A(_267_),
    .B(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o21ai_0 _580_ (
    .A1(_265_),
    .A2(_266_),
    .B1(count[7]),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nand2_1 _581_ (
    .A(_270_),
    .B(_271_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand4_1 _582_ (
    .A(count[5]),
    .B(count[4]),
    .C(count[7]),
    .D(count[6]),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor2_1 _583_ (
    .A(_272_),
    .B(_262_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__xor2_1 _584_ (
    .A(count[8]),
    .B(_273_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _585_ (
    .A1(_273_),
    .A2(count[8]),
    .B1(count[9]),
    .Y(_274_)
  );
  sky130_fd_sc_hd__clkinv_1 _586_ (
    .A(count[9]),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _587_ (
    .A(_273_),
    .B(count[8]),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nor2_1 _588_ (
    .A(_275_),
    .B(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nor2_1 _589_ (
    .A(_274_),
    .B(_277_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _590_ (
    .A1(_275_),
    .A2(_276_),
    .B1(count[10]),
    .Y(_278_)
  );
  sky130_fd_sc_hd__clkinv_1 _591_ (
    .A(count[10]),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nand2_1 _592_ (
    .A(_277_),
    .B(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nand2_1 _593_ (
    .A(_280_),
    .B(_278_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _594_ (
    .A(count[11]),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand3_1 _595_ (
    .A(_277_),
    .B(_281_),
    .C(count[10]),
    .Y(_282_)
  );
  sky130_fd_sc_hd__o31ai_1 _596_ (
    .A1(_275_),
    .A2(_279_),
    .A3(_276_),
    .B1(count[11]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nand2_1 _597_ (
    .A(_282_),
    .B(_283_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand4_1 _598_ (
    .A(count[9]),
    .B(count[8]),
    .C(count[11]),
    .D(count[10]),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nor3_1 _599_ (
    .A(_272_),
    .B(_284_),
    .C(_262_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__xor2_1 _600_ (
    .A(count[12]),
    .B(_285_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _601_ (
    .A(_285_),
    .B(count[12]),
    .Y(_286_)
  );
  sky130_fd_sc_hd__xnor2_1 _602_ (
    .A(count[13]),
    .B(_286_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand4_1 _603_ (
    .A(_285_),
    .B(count[13]),
    .C(count[12]),
    .D(count[14]),
    .Y(_287_)
  );
  sky130_fd_sc_hd__a31oi_1 _604_ (
    .A1(_285_),
    .A2(count[13]),
    .A3(count[12]),
    .B1(count[14]),
    .Y(_288_)
  );
  sky130_fd_sc_hd__and2b_2 _605_ (
    .A_N(_288_),
    .B(_287_),
    .X(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _606_ (
    .A(count[15]),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nand2_1 _607_ (
    .A(_287_),
    .B(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand4_1 _608_ (
    .A(count[13]),
    .B(count[12]),
    .C(count[15]),
    .D(count[14]),
    .Y(_291_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(_284_),
    .B(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nand2_1 _610_ (
    .A(_273_),
    .B(_292_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__and2_2 _611_ (
    .A(_290_),
    .B(_293_),
    .X(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _612_ (
    .A(count[16]),
    .Y(_294_)
  );
  sky130_fd_sc_hd__xor2_1 _613_ (
    .A(_294_),
    .B(_293_),
    .X(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _614_ (
    .A(count[17]),
    .Y(_295_)
  );
  sky130_fd_sc_hd__nand3_1 _615_ (
    .A(_273_),
    .B(count[16]),
    .C(_292_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__xor2_1 _616_ (
    .A(_295_),
    .B(_296_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _617_ (
    .A(_295_),
    .B(_294_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__nand3_1 _618_ (
    .A(_273_),
    .B(_292_),
    .C(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__xnor2_1 _619_ (
    .A(count[18]),
    .B(_298_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a41oi_1 _620_ (
    .A1(_273_),
    .A2(count[18]),
    .A3(_292_),
    .A4(_297_),
    .B1(count[19]),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nand4_1 _621_ (
    .A(count[17]),
    .B(count[16]),
    .C(count[19]),
    .D(count[18]),
    .Y(_300_)
  );
  sky130_fd_sc_hd__clkinv_1 _622_ (
    .A(_300_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__a31oi_1 _623_ (
    .A1(_273_),
    .A2(_292_),
    .A3(_301_),
    .B1(_299_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _624_ (
    .A(count[20]),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nand3_1 _625_ (
    .A(_273_),
    .B(_292_),
    .C(_301_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__xor2_1 _626_ (
    .A(_302_),
    .B(_303_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand4_1 _627_ (
    .A(_273_),
    .B(count[20]),
    .C(_292_),
    .D(_301_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__xnor2_1 _628_ (
    .A(count[21]),
    .B(_304_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _629_ (
    .A(count[22]),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nand2_1 _630_ (
    .A(count[21]),
    .B(count[20]),
    .Y(_306_)
  );
  sky130_fd_sc_hd__clkinv_1 _631_ (
    .A(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__nand4_1 _632_ (
    .A(_273_),
    .B(_292_),
    .C(_301_),
    .D(_307_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__xor2_1 _633_ (
    .A(_305_),
    .B(_308_),
    .X(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _634_ (
    .A(count[23]),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor2_1 _635_ (
    .A(_305_),
    .B(_308_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nand2_1 _636_ (
    .A(_310_),
    .B(_309_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__o21ai_0 _637_ (
    .A1(_305_),
    .A2(_308_),
    .B1(count[23]),
    .Y(_312_)
  );
  sky130_fd_sc_hd__nand2_1 _638_ (
    .A(_311_),
    .B(_312_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor4_1 _639_ (
    .A(_309_),
    .B(_305_),
    .C(_306_),
    .D(_300_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__nand3_1 _640_ (
    .A(_273_),
    .B(_292_),
    .C(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__xor2_1 _641_ (
    .A(_067_),
    .B(_314_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand4_1 _642_ (
    .A(_273_),
    .B(count[24]),
    .C(_292_),
    .D(_313_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__xor2_1 _643_ (
    .A(_066_),
    .B(_315_),
    .X(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _644_ (
    .A(count[26]),
    .Y(_316_)
  );
  sky130_fd_sc_hd__nor2_1 _645_ (
    .A(_066_),
    .B(_067_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nand4_1 _646_ (
    .A(_273_),
    .B(_292_),
    .C(_313_),
    .D(_317_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__xor2_1 _647_ (
    .A(_316_),
    .B(_318_),
    .X(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _648_ (
    .A(count[27]),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _649_ (
    .A(_316_),
    .B(_318_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nand2_1 _650_ (
    .A(_320_),
    .B(_319_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__o21ai_0 _651_ (
    .A1(_316_),
    .A2(_318_),
    .B1(count[27]),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nand2_1 _652_ (
    .A(_321_),
    .B(_322_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__buf_1 _653_ (
    .A(state[1]),
    .X(light_highway[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _654_ (
    .CLK(clk),
    .D(_000_),
    .Q(delay10s)
  );
  sky130_fd_sc_hd__dfxtp_1 _655_ (
    .CLK(clk),
    .D(_001_),
    .Q(count_delay[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _656_ (
    .CLK(clk),
    .D(_002_),
    .Q(count_delay[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _657_ (
    .CLK(clk),
    .D(_003_),
    .Q(count_delay[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _658_ (
    .CLK(clk),
    .D(_004_),
    .Q(count_delay[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _659_ (
    .CLK(clk),
    .D(_005_),
    .Q(count_delay[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _660_ (
    .CLK(clk),
    .D(_006_),
    .Q(count_delay[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _661_ (
    .CLK(clk),
    .D(_007_),
    .Q(count_delay[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _662_ (
    .CLK(clk),
    .D(_008_),
    .Q(count_delay[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _663_ (
    .CLK(clk),
    .D(_009_),
    .Q(count_delay[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _664_ (
    .CLK(clk),
    .D(_010_),
    .Q(count_delay[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _665_ (
    .CLK(clk),
    .D(_011_),
    .Q(count_delay[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _666_ (
    .CLK(clk),
    .D(_012_),
    .Q(count_delay[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _667_ (
    .CLK(clk),
    .D(_013_),
    .Q(count_delay[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _668_ (
    .CLK(clk),
    .D(_014_),
    .Q(count_delay[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _669_ (
    .CLK(clk),
    .D(_015_),
    .Q(count_delay[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _670_ (
    .CLK(clk),
    .D(_016_),
    .Q(count_delay[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _671_ (
    .CLK(clk),
    .D(_017_),
    .Q(count_delay[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _672_ (
    .CLK(clk),
    .D(_018_),
    .Q(count_delay[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _673_ (
    .CLK(clk),
    .D(_019_),
    .Q(count_delay[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _674_ (
    .CLK(clk),
    .D(_020_),
    .Q(count_delay[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _675_ (
    .CLK(clk),
    .D(_021_),
    .Q(count_delay[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _676_ (
    .CLK(clk),
    .D(_022_),
    .Q(count_delay[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _677_ (
    .CLK(clk),
    .D(_023_),
    .Q(count_delay[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _678_ (
    .CLK(clk),
    .D(_024_),
    .Q(count_delay[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _679_ (
    .CLK(clk),
    .D(_025_),
    .Q(count_delay[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _680_ (
    .CLK(clk),
    .D(_026_),
    .Q(count_delay[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _681_ (
    .CLK(clk),
    .D(_027_),
    .Q(count_delay[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _682_ (
    .CLK(clk),
    .D(_028_),
    .Q(count_delay[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _683_ (
    .CLK(clk),
    .D(_029_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _684_ (
    .CLK(clk),
    .D(_030_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _685_ (
    .CLK(clk),
    .D(_031_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _686_ (
    .CLK(clk),
    .D(_032_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _687_ (
    .CLK(clk),
    .D(_033_),
    .Q(count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _688_ (
    .CLK(clk),
    .D(_034_),
    .Q(count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _689_ (
    .CLK(clk),
    .D(_035_),
    .Q(count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _690_ (
    .CLK(clk),
    .D(_036_),
    .Q(count[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _691_ (
    .CLK(clk),
    .D(_037_),
    .Q(count[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _692_ (
    .CLK(clk),
    .D(_038_),
    .Q(count[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _693_ (
    .CLK(clk),
    .D(_039_),
    .Q(count[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _694_ (
    .CLK(clk),
    .D(_040_),
    .Q(count[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _695_ (
    .CLK(clk),
    .D(_041_),
    .Q(count[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _696_ (
    .CLK(clk),
    .D(_042_),
    .Q(count[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _697_ (
    .CLK(clk),
    .D(_043_),
    .Q(count[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _698_ (
    .CLK(clk),
    .D(_044_),
    .Q(count[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _699_ (
    .CLK(clk),
    .D(_045_),
    .Q(count[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _700_ (
    .CLK(clk),
    .D(_046_),
    .Q(count[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _701_ (
    .CLK(clk),
    .D(_047_),
    .Q(count[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _702_ (
    .CLK(clk),
    .D(_048_),
    .Q(count[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _703_ (
    .CLK(clk),
    .D(_049_),
    .Q(count[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _704_ (
    .CLK(clk),
    .D(_050_),
    .Q(count[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _705_ (
    .CLK(clk),
    .D(_051_),
    .Q(count[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _706_ (
    .CLK(clk),
    .D(_052_),
    .Q(count[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _707_ (
    .CLK(clk),
    .D(_053_),
    .Q(count[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _708_ (
    .CLK(clk),
    .D(_054_),
    .Q(count[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _709_ (
    .CLK(clk),
    .D(_055_),
    .Q(count[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _710_ (
    .CLK(clk),
    .D(_056_),
    .Q(count[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _711_ (
    .CLK(clk),
    .D(_057_),
    .Q(delay3s1)
  );
  sky130_fd_sc_hd__dfxtp_1 _712_ (
    .CLK(clk),
    .D(_058_),
    .Q(delay3s2)
  );
  sky130_fd_sc_hd__dfrtp_1 _713_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _714_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
endmodule
